# Default values for cilium-chaining.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  # global.nameOverride
  nameOverride: ""

  # global.imageRegistryOverride
  imageRegistryOverride: ""

  # global.labels the global labels of this chart
  labels: {}

  # global.labels the global annotations of this chart
  annotations: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cilium:
  image:
    # cilium.image.registry the registry of the cilium-chaining
    registry: ghcr.io

    # cilium.image.repository the repository of the cilium-chaining
    repository: spidernet-io/cilium-chaining

    # cilium.image.pullPolicy the image pullPolicy of the cilium-chaining
    pullPolicy: IfNotPresent

    # cilium.image.tag Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # cilium.enableInClusterLoadbalance enable short circuit for in cluster traffic to externalIP and loadBalancerIP
  enableInClusterLoadbalance: true

  # cilium.policyEnforcement Enable policy enforcement (default "default"), available options: [default,always,never]
  policyEnforcement: default

  # cilium.kubeProxyReplacement enable only selected features ("partial"), or enable all features ("strict"), or completely disable it (ignores any selected feature) ("disabled") (default "partial")
  kubeProxyReplacement: partial

  # cilium.enableBandwidthManager enable bandwidth manager to optimize TCP and UDP workloads and allow
  # for rate-limiting traffic from individual Pods with EDT
  enableBandwidthManager: false

  # cilium.labels the labels of the cilium-chaining pod
  labels: {}

  # cilium.annotations the annotations of the cilium-chaining pod
  annotations: {}

  # cilium.affinity the affinity of cilium-chaining pod
  affinity: {}

  resources:
    limits:
      # cilium.resources.limits.cpu the cpu limit of the cilium-chaining pod
      cpu: 1000m

      # cilium.resources.limits.cpu the memory limit of the cilium-chaining pod
      memory: 1024Mi
    requests:
      # cilium.resources.requests.cpu the cpu limit of the cilium-chaining pod
      cpu: 250m

      # cilium.resources.requests.memory the memory limit of the cilium-chaining pod
      memory: 300Mi

hubble:
  # hubble.enabled enable hubble
  enabled: false

  # hubble.metrics List of Hubble metrics to enable, multi metrics separated by common
  metrics: ""

serviceAccount:
  # serviceAccount.create create serviceAccount for cilium-chaining pod
  create: true

  # serviceAccount.name the name of the serviceAccount
  name: cilium-chaining

  # serviceAccount.annotations the annotations of the serviceAccount
  annotations: {}